env:
  browser: true
  commonjs: true
  es2021: true
parser:
  vue-eslint-parser
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
  - 'prettier'
parserOptions:
  parser: '@typescript-eslint/parser'
  extraFileExtensions:
    - .vue
  ecmaVersion: 12
rules: 
  indent: ['error', 2, { SwitchCase: 1 }]
  quotes: ['error', 'single']
  semi: ['error', 'never']
  # 烦死了
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': 0